### ISSUE TITLE
eas-cli submit Redundant Binary Upload

### ISSUE THREAD

**Issue by mahaupt** [expo/eas-cli#1176]
### Build/Submit details page URL

https://expo.dev/accounts/menero/projects/menero-gastro/submissions/c1e47209-7e01-43aa-929d-ed1c82cfb396

### Summary

Building is successful, however if I try to submit either ios or android version, the submission fails because of redundant binary upload. It thinks the build number is 0.0.1 which is odd.

```ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.0.1' for version number '0.0.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."```

To build and submit, I use github actions CI with the following command:
```yaml
      - name: eas build main
        if: github.ref == 'refs/heads/main'
        env:
          APP_BUILD_NUMBER: ${{ github.run_number }}
          APP_VERSION: ${{ steps.latestVersion.outputs.version }}
        run: npx eas-cli build --platform all --profile production --non-interactive --no-wait --auto-submit
```

My app.config.js
```
export default ({ config }) => {
  config.version = process.env.APP_VERSION || "0.0.1";
  config.ios.buildNumber = process.env.APP_BUILD_NUMBER || "0.0.1";
  config.android.versionCode = parseInt(process.env.APP_BUILD_NUMBER) || 1;
  return config;
}
```

### Managed or bare?

managed

### Environment

```
 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.5 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

will be provided shortly
