### ISSUE TITLE
Provisioning profile "*[expo] XXX AdHoc XXX" doesn't include signing certificate "Apple Distribution: XXX"

### ISSUE THREAD

**Issue by rcarter** [expo/eas-cli#1201]
### Build/Submit details page URL

https://expo.dev/accounts/XXXXXXX/projects/XXXXXXXX/builds/253dc20a-ffb0-40f9-9707-cff2c0f6575d

### Summary

All of a sudden, with no changes to my certs/profiles when I run: `eas build --platform ios`

I’m running into:
`:x: error: Provisioning profile "*[expo] XXX AdHoc XXX" doesn't include signing certificate "Apple Distribution: XXX".`

I’ve deleted all my provisioning profiles and certs and am letting eas handle creating new ones. But still the same error (both when running `--local` as well as running in the cloud). I recently upgraded to `eas-cli/0.54.1` and I think it started happening after that upgrade. I can’t get any build past this.

### Managed or bare?

Managed

### Environment

```expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-30 | ARM 64 v8a, android-30 | Google APIs Intel x86 Atom_64, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.9
    Expo Workflow: managed```
    
`🎉 Didn't find any issues with the project!`

### Error output

_No response_

### Reproducible demo or steps to reproduce from a blank project

not reproducible.

**Comment by izakfilmalter** [comment]
I am having the same issue, how did you fix it?

**Comment by rcarter** [comment]
@izakfilmalter I can't exactly remember, but I deleted any certs in my Login Keychain, created new certs in AppStoreConnect, then downloaded and installed them back into my keychain. I took me a bit to get it right!

**Comment by izakfilmalter** [comment]
Thanks, that solved it for me. Was super confused with what is going on.

**Comment by umbertoghio** [comment]
I keep stumbling every once in a while in this issue, writing as reminder what specifically solved my issue:

In keychain access, under Login, my certificates, delete all "Apple Distribution: ......" Certificates, then no need to download / do anything else, it just works.

**Comment by km-tr** [comment]
Thanks, I deleted the Apple Distribution certificate from my keychain and that solved it.

**Comment by dongsuo** [comment]
@umbertoghio Thank you bro, you save my day

**Comment by Acetyld** [comment]
Thank you! @umbertoghio also saved my day =)

**Comment by fluid-design-io** [comment]
Thanks! This worked for me as well!
For people who are using *local* eas build, if your build failed an want to see the logs, in the terminal, export the env `export EAS_LOCAL_BUILD_SKIP_CLEANUP=1`and you'll see the console show a dir with the build logs, something like this:
`Skipping cleanup, /var/folders/.../ won't be removed.`

**Comment by Dinexpod** [comment]
> I keep stumbling every once in a while in this issue, writing as reminder what specifically solved my issue:
> 
> In keychain access, under Login, my certificates, delete all "Apple Distribution: ......" Certificates, then no need to download / do anything else, it just works.

Thanks A LOT, you so helpful, this problem exhausts me)

**Comment by arncet** [comment]
> I keep stumbling every once in a while in this issue, writing as reminder what specifically solved my issue:
> 
> In keychain access, under Login, my certificates, delete all "Apple Distribution: ......" Certificates, then no need to download / do anything else, it just works.

Works for me too :)
Thank you so much !!

**Comment by AnthonyGress** [comment]
Removing it solved it for me as well. Build error was an ARCHIVE ERROR exit code 65. Looking into the xcode build logs showed it was a mismatch with my distribution certificate.

**Comment by felipejh** [comment]
Removing solved for me, but it brings problems to build another app I have.

**Comment by NaokiOtsu** [comment]
As @felipejh said, deleting Apple Distribution: ...... solved the problem, but when I try to build another desktop app for the Mac App Store, I get an error because the Apple Distribution file is missing.

It would be nice if there was a way to prevent the iOS build from failing while leaving the Apple Distribution: ...... file, but I'm not sure how to do this.

**Comment by ekimcem** [comment]
> I keep stumbling every once in a while in this issue, writing as reminder what specifically solved my issue:
> 
> In keychain access, under Login, my certificates, delete all "Apple Distribution: ......" Certificates, then no need to download / do anything else, it just works.

Dear Hero,

I will pray for you at least 4-5 days more after my release is done.

If only I had witnessed your ultimately perfectful genius suggestion just a few hours—or maybe days—earlier...

**Comment by matheuscouto** [comment]
> > I keep stumbling every once in a while in this issue, writing as reminder what specifically solved my issue:
> > In keychain access, under Login, my certificates, delete all "Apple Distribution: ......" Certificates, then no need to download / do anything else, it just works.
> 
> Dear Hero,
> 
> I will pray for you at least 4-5 days more after my release is done.
> 
> If only I had witnessed your ultimately perfectful genius suggestion just a few hours—or maybe days—earlier...

I’ll second that

**Comment by skrobot** [comment]
Saved my day!

**Comment by tahahaz1374** [comment]
Removing it solved the issue for me, but it causes problems when building another app I have.
It’s just a temporary workaround, not a real solution.

**Comment by shirakaba** [comment]
I think I've got an idea of the root cause.

Follow along with me to see my reasoning. First, do a local build as follows:

```sh
EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build --non-interactive --platform ios --profile preview --local
```

By passing `EAS_LOCAL_BUILD_SKIP_CLEANUP=1`, you'll get this message telling you where to look for your build artifacts:

> Skipping cleanup, /var/folders/0m/nf10bfxx6rgft8tn29fznymc0000gn/T/eas-build-local-nodejs/537a3b7d-968f-4dc4-b370-fa28040adfa3 won't be removed.

Have a look inside that directory that it's talking about. The contents will look like this:

```
├── artifacts
├── bin
│  └── set-env
├── build
│  ├── README.md
│  ├── android
│  ├── app.json
│  ├── assets
│  ├── babel.config.js
│  ├── eas.json
│  ├── index.ts
│  ├── ios
│  │   ├── Gymfile
│  │   ├── Podfile
│  │   ├── Podfile.lock
│  │   ├── Podfile.properties.json
│  │   ├── Pods
│  │   ├── build
│  │   ├── banana
│  │   ├── banana.xcodeproj
│  │   ├── banana.xcworkspace
│  │   └── sentry.properties
│  ├── metro.config.js
│  ├── modules
│  ├── node_modules
│  ├── package.json
│  └── tsconfig.json
├── custom-build
├── env
├── logs
│  └── banana-banana.log
├── project.tar.gz
└── temporary-custom-build
```

You'll see it contains a copy of your repo, with dependencies installed and the app built! Let's look inside `build/ios/Gymfile`:


```ruby
suppress_xcode_output(true)
clean(false)

scheme("noman")

configuration("Release")


export_options({
  method: "ad-hoc",
  provisioningProfiles: {
    "com.fruitco.banana" => "6065a805-3f2a-4ee6-ad7b-61ee86a8b031",
  }
})

export_xcargs "OTHER_CODE_SIGN_FLAGS=\"--keychain /var/folders/0m/nf10bfxx6rgft8tn29fznymc0000gn/T/eas-build-9938ac9e-9359-4ff6-82e5-a75e5844dc1a.keychain\""

disable_xcpretty(true)
buildlog_path("/var/folders/0m/nf10bfxx6rgft8tn29fznymc0000gn/T/eas-build-local-nodejs/537a3b7d-968f-4dc4-b370-fa28040adfa3/logs")

output_directory("./build")
```

I think EAS is inheriting a [problem](https://github.com/fastlane/fastlane/issues/21407#issuecomment-1959237846) that other Fastlane users run into. For some background, our provisioning profile contains an `iPhone Distribution` certificate. If you look inside your `build/ios/banana.xcodeproj` (which, is either generated during that build by Expo Prebuild, or checked out from source, depending on your `.gitignore` and `.easignore` settings), you may even see in the build settings for configuration Release, we're correctly specifying:

```
PROVISIONING_PROFILE_SPECIFIER = "*[expo] com.fruitco.banana AdHoc 1763476269847";
CODE_SIGN_IDENTITY = "iPhone Distribution";
CODE_SIGN_STYLE = Manual;
```

My hypothesis is that Gym defaults to expecting the more modern "Apple Distribution" certificate type, which is at odds with our provisioning profile due to it containing the legacy "iPhone Distribution" certificate type.

So I think we need to explicitly specify it to help it along. Looking at the parameters for [export_options](https://docs.fastlane.tools/actions/build_ios_app/#parameters), maybe something like this:

```diff
  export_options({
    method: "ad-hoc",
    provisioningProfiles: {
+     "codesigning_identity" => "iPhone Distribution",
      "com.fruitco.banana" => "6065a805-3f2a-4ee6-ad7b-61ee86a8b031",
    }
  })
```

It sounds like EAS lets us [customise the Gymfile](https://docs.expo.dev/build-reference/ios-builds/#default-gymfile).

So I intend to try that and see how it goes. But it's bedtime soon and I've got the day off tomorrow, so will report back once I've tried it. Hope this helps someone.

P.S.

Alternatively, we could try to provide it with a provisioning profile that uses the more modern `Apple Distribution` instead of `iPhone Distribution`. I don't know what's involved with that, because I'm just dropping in to a project that someone else set up. If it's EAS that defaults to generating `iPhone Distribution`, then I think the Expo team should default to generating `Apple Distribution` instead to avoid this issue. `Apple Distribution` is a superior certificate, because it can sign macOS apps as well, so it avoids eating into your organisation's maximum generated certificates limit more than you have to.

**Comment by bestofaIl** [comment]
@shirakaba 
Thanks for the detailed investigation you shared earlier — it was really helpful and clearly laid out.
Just wanted to check in and ask whether you’ve had a chance to try out your proposed solution.
Any updates on how it went would be greatly appreciated!

**Comment by shirakaba** [comment]
Not yet! Still on my day off 😄 fixing [another](https://x.com/birch_js/status/1991073243189452928?s=20) React Native problem today instead.

Hoping to get my hands on it by the end of this week.

**Comment by shirakaba** [comment]
# Update on my previous comment

@bestofaIl  Adding `"codesigning_identity" => "iPhone Distribution",` into the Gymfile didn't help.

# Actual solution

## Review your current codesigning setup

Go to your EAS Credentials page:

<img width="1261" height="665" alt="Image" src="https://github.com/user-attachments/assets/a3c33f9e-ec56-4ce8-8414-0135ee4ff440" />

In this image, you see:

1. A distribution certificate, `31AFF1187BC3A3C91D9122318D4E5GA0`.
  - This is your `iPhone Distribution` (labelled as `iOS Distribution` on developer.apple.com) certificate.
2. A provisioning profile, `fd6ae759-7120-4356-ac4f-fee22a9dc661`.
  - This profile references that certificate.

You need to edit that provisioning profile so that it contains the more modern `Apple Distribution` (labelled as `Distribution` on developer.apple.com) certificate.

## Editing the provisioning profile

Go to [Certificate, Identifiers, & Profiles](https://developer.apple.com/account/resources/profiles/list) on developer.apple.com.

Select the provisioning profile (it should be the one with a name like `*[expo] com.fruitco.banana AdHoc 1763440689949`, with platform `iOS` and type `Ad hoc`). Now edit it.

<img width="1280" height="1410" alt="Image" src="https://github.com/user-attachments/assets/a8ceb428-b3bd-4e92-b35c-f59e5b76ee38" />

Currently, the selected certificate is of type `iPhone Distribution`. Change that to `Distribution` (which is apple.developer.com's label for `Apple Distribution`). If you don't have one yet, go and issue one first, then come back. Once you've made the change, click 'save'.

Once the change is saved, a download button is presented. Download it, and you'll get a file named `[expo]_comfruitcobanana_AdHoc_1763440589949.mobileprovision` (which is the updated provisioning profile).

## Updating the EAS Credentials

### Updating the provisioning profile

Back on the EAS Credentials page, you need to replace the old provisioning profile (although we 'edited' the provisioning profile just now, what Apple actually does is issue a whole new profile with a distinct UUID and SHA-1 hash, so really it's more like we created a new one using that as a template) with the `[expo]_comfruitcobanana_AdHoc_1763440589949.mobileprovision` you just generated.

You can do that either by editing the currently-selected one, or deleting it and uploading a new one. It's the same result either way.

### Updating the certificate

Here, we aim to upload the private key (`.p12` file) for the same `Distribution` certificate that went into the provisioning profile we just generated.

Personally, I did this by the following steps:

1. Open Xcode.
2. Select `Settings...` from the Apple menu.
3. Select the `Apple Accounts` tab. 
4. Select your Apple account.
5. Select your developer team.
6. Click "Download Manual Profiles".

I believe this gets the certificate and its private key onto your computer and stores it into your Keychain. I may be wrong.

Now open the Keychain Access app (it comes with macOS):

<img width="1020" height="640" alt="Image" src="https://github.com/user-attachments/assets/216f1840-6aaa-4518-be46-e94aa4bfaf68" />

You want to find the same certificate that went into that provisioning profile. Use Quick Look on `[expo]_comfruitcobanana_AdHoc_1763440589949.mobileprovision` to see which certificate is inside it; it'll tell you the serial number and the SHA-1 hash.

You can see more details about each certificate in Keychain Access by double-clicking each one. Search for the one the matching SHA-1 hash.

Once you've found the certificate, right-click it and export it (what that means is to export the `.p12` private key). When it prompts you to make a password to encrypt it, provide a password and store that password into your password manager for later.

You now have the private key for the certificate. On the EAS Credentials page, replace the currently-selected `iOS Distribution` one with this `Distribution` one. You’ll need to provide the encryption password (you did save it into your password manager, right?).

That's all. Phew! You're now finished. The next time you sign, the EAS CLI will use that provisioning profile and certificate private key to sign, and it'll be happy because now the provisioning profile indeed contains an `Apple Distribution` certificate.

**Comment by bestofaIl** [comment]
@shirakaba 
Thanks a lot for staying so actively involved in getting to the bottom of this issue — your follow-up and the alternative approach with replacing the certificate are really appreciated.

I’ve also made some progress on my side in understanding and addressing the problem.
Let me outline the details in the next update.


I was initially trying to follow your suggestion to modify the Gymfile directly, but in practice that turned out to be more complicated than expected.

In the end, I switched to using Expo’s custom builds feature — [https://docs.expo.dev/custom-builds/schema/](https://docs.expo.dev/custom-builds/schema/) — and overrode the default Gymfile template.
I’ll skip all the failed attempts and go straight to the template that finally allowed me to produce a properly signed IPA.

**In `.eas/build/production-build-ios.yml`:**

```yaml
# this config is executed when running a build with `ios-build-with-credentials` profile
# check the profile's configuration in eas.json to see what are the settings needed to execute it properly

build:
  name: iOS build with credentials build as executed by the eas/build command
  steps:
    - eas/checkout
    - eas/install_node_modules
    - eas/resolve_build_config

    - eas/resolve_apple_team_id_from_credentials:
        id: resolve_apple_team_id_from_credentials

    - eas/prebuild:
        inputs:
          apple_team_id: ${ steps.resolve_apple_team_id_from_credentials.apple_team_id }

    - run:
        name: Install pods
        working_directory: ./ios
        command: pod install

    - eas/configure_ios_credentials
    - eas/configure_ios_version

    - eas/generate_gymfile_from_template:
        inputs:
          credentials: ${ eas.job.secrets.buildCredentials }
          template: |
            suppress_xcode_output(true)
            clean(<%- CLEAN %>)
            
            scheme("<%- SCHEME %>")
            <% if (BUILD_CONFIGURATION) { %>
            configuration("<%- BUILD_CONFIGURATION %>")
            <% } %>
            
            # very important — this took me a while to figure out
            codesigning_identity("iPhone Distribution: xxxx xxxx (xxxxxxxxxx)")
            
            export_options({
              method: "<%- EXPORT_METHOD %>",
              provisioningProfiles: {<% _.forEach(PROFILES, function(profile) { %>
                "<%- profile.BUNDLE_ID %>" => "<%- profile.UUID %>",<% }); %>
              }<% if (ICLOUD_CONTAINER_ENVIRONMENT) { %>,
              iCloudContainerEnvironment: "<%- ICLOUD_CONTAINER_ENVIRONMENT %>"
              <% } %>,
              signingCertificate: "iPhone Distribution: xxxx xxxx (xxxxxxxxxx)"
            })
            
            export_xcargs "OTHER_CODE_SIGN_FLAGS=\"--keychain <%- KEYCHAIN_PATH %>\""
            
            disable_xcpretty(true)
            buildlog_path("<%- LOGS_DIRECTORY %>")
            
            output_directory("<%- OUTPUT_DIRECTORY %>")

    - eas/run_fastlane
    - eas/find_and_upload_build_artifacts
```

**In `eas.json`:**

```json
{
  "build": {
    "production": {
      "config": "production-build-ios.yml",
      "env": {
        "EXPO_PUBLIC_BUILD": "production"
      }
    }
  }
}
```

And then I run the build like this:

```
npx eas-cli build -p ios --profile production --local --non-interactive --output ./build/app.ipa
```

Hopefully this helps someone save some time.
