### ISSUE TITLE
Running eas init from CI/CD getting "Error: Input is required, but stdin is not readable"

### ISSUE THREAD

**Issue by monelgordillo** [expo/eas-cli#1424]
I'm running eas init from CI/CD getting "Error: Input is required, but stdin is not readable".

I'm guessing eas init is a relatively new requirement.

Is there no way to run eas init non-interactively?

**Comment by jparksecurity** [comment]
I'm having the same error on GitLab CICD when running `eas secret:create`

**Comment by monelgordillo** [comment]
I got around having to run eas init at all by add this to app.json:

    "extra": {
      "eas": {
        "projectId": "project-id-listed-on-expo"
      }
    }

I'm not really sure why its complaining about the stdin issue.  I should be able to run all eas commands from the CLI non-interactively.  :/

**Comment by jparksecurity** [comment]
I started having this issue since `eas-cli@2.2.0`

My pipeline worked just fine with `eas-cli@2.1.0`

**Comment by dsokal** [comment]
Hi guys, 
You should never need to run `eas init` in CI. This command should be executed only once locally. Remember to commit the changes it made to the repo.

**Comment by jparksecurity** [comment]
@dsokal I want to clarify what I did. I didn't run `eas init` but `eas secret:create --name $name --value $value --force`.

I had to change it to `eas secret:create --name $name --value $value --force --non-interactive --type string`

I expect `eas secret:create`(`eas-cli@2.2.0`) to work the same as `eas-cli@2.1.0`.

Or if the required options are added to this command, I wish an error message to be clear instead of `Error: Input is required, but stdin is not readable`.

I know it is easy to fix even with the current error message, but how do I know what to do right away with the current message?

**Comment by dsokal** [comment]
It's always recommended to use fixed tools versions in CI environments. Thanks to that you're never surprised by breaking changes in 3rd party tools. With fixed versions, nothing is upgraded without your knowledge. 

In this particular case, we didn't follow the semver conventions with the `2.2.0` release. Sorry about this inconvenience. We'll try to avoid similar mistakes in the future. Sorry again 🙇

**Comment by sean-m-oleary** [comment]
I have the exact same issue and it started with eas-cli@2.2.0 also. For me it is when running eas build using the following command:

npx eas-cli build --profile=test --non-interactive --platform=all

What's the fix??

**Comment by bj97301** [comment]
i am getting this error as well

**Comment by zerodeleo** [comment]
I'm getting this error as well, running `eas build --platform android --profile preview`

**Comment by falk-stefan** [comment]
Coming over from https://github.com/expo/eas-cli/issues/1470 - I get the same error running a build via GitHub Actions.

**Comment by jakegreenbergbell** [comment]
I'm also coming from #1470 and have the issue when running a build with Github Actions.

**Comment by TonyBobins** [comment]
I manually set a git safe dir in my Github Actions workflow and it solved the issue with `eas build` for me. 
```yaml
steps:
  - name: 📦 Checkout project repo
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  # Checkout action doesn't set safe dir for some reason
  - name: 📝 Configure Git safe directory
    run: git config --global --add safe.directory $GITHUB_WORKSPACE
    
  # ... your `expo prebuild` and `eas build` steps ...
```

**Comment by sdharmarajah** [comment]
Hi, none of these solutions worked for me unfortunately.

I even tried to define the required variables as ENV variables (since this works locally for me) with the following ```YAML``` Github Action:

```      
- name: Trigger EAS Build
        run: eas build --profile ${{ github.event.inputs.branch || github.ref_name }} --platform android --message "Build ${{ github.event.inputs.branch || github.sha }}"
        shell: bash
        env:
          ANDROID_KEYSTORE_FILE: android/app/my-release-key.keystore
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
```
However I'm still getting an error:

```Specified value for "android.package" in app.config.ts is ignored because an android directory was detected in the project.
EAS Build will use the value found in the native code.
✔ Using remote Android credentials (Expo server)
Input is required, but stdin is not readable. Failed to display prompt: Generate a new Android Keystore?
    Error: build command failed.
Error: Process completed with exit code 1.```
