### ISSUE TITLE
EAS Update only publishing to HEAD in CI

### ISSUE THREAD

**Issue by nkrekow** [expo/eas-cli#1512]
### Build/Submit details page URL

https://expo.dev/accounts/wanderapp/projects/wander/branches/HEAD

### Summary

In our GH Action workflows we have one to publish updates for dev PRs using the following command (same as what the docs specify)
```
- name: 🚀 Publish preview
        run: eas update --auto
```

However, when running in GH Actions for whatever reason instead of publishing to a branch based on the current branch name and with the message of latest commit it is instead publishing ALL updates for ever PR and branch to a single branch called HEAD with the same message (Merge xxxxx into xxxxx) essentially making updates unusable.

If you run this same command locally then it works as expected, a new branch is created based on the current git branch name with a message equal to latest commit.

The only thing different in our GH action config from the version in the expo docs is we have git lfs enabled on the setup repo step.

### Managed or bare?

Bare

### Environment

Expo env info
``` 
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.14.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```

Expo doctor
```
Expected package @expo/config-plugins@^5.0.2
Found invalid:
  @expo/config-plugins@5.0.1
  @expo/config-plugins@5.0.1
  @expo/config-plugins@5.0.1
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^5.0.5
Found invalid:
  @expo/prebuild-config@5.0.3
  (for more info, run: npm why @expo/prebuild-config)
```

### Reproducible demo or steps to reproduce from a blank project

Copy of our GH Workflow action is below:
```
name: development

on: pull_request

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
      - name: ❌ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-latest
    needs: cancel
    timeout-minutes: 10

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🧪 Lint
        continue-on-error: true
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    needs: cancel
    timeout-minutes: 10
    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🧪 Unit & Integration tests
        continue-on-error: true
        run: yarn test:ci

      - name: 💬 Report coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./jest-report.json
          base-coverage-file: ./jest-report.json
  
  publish:
    runs-on: ubuntu-latest
    needs: cancel
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🚀 Publish preview
        run: eas update --auto

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
```
