### ISSUE TITLE
GitHub Action build iOS local failing 

### ISSUE THREAD

**Issue by LBeghini** [expo/eas-cli#1682]
### Summary

I am trying to build an iOS app using the GitHub Actions. For that, I am trying to build locally to use the resources of GitHub and ease the process of releasing the apps on GitHub itself, since those are just for testing purposes.

I generated the `provisioningProfilePath` and the `distributionCertificate` following the tutorial:
- [Creating the iOS Provisioning Profiles](https://support.staffbase.com/hc/en-us/articles/115003598691-Creating-the-iOS-Provisioning-Profiles)
- [Creating the iOS Distribution Certificate](https://support.staffbase.com/hc/en-us/articles/115003458931-Creating-the-iOS-Distribution-Certificate)

> Yes I have an Apple Store Developer Account

In my pipeline I am setting up:
- Android SDK Tools
- Fastlane
- Expo

As I am using the MacOS system, I am relying on the provided XCode.

To build, I am using the following command:
```bash
eas build --platform ios --profile release --local --non-interactive
```

### Managed or bare?

Bare

### Environment

As it runs on the pipeline I do not have this information

### Error output

```bash
[RUN_EXPO_DOCTOR] Command "expo doctor" failed.
Error: bash exited with signal: SIGTERM
[PREPARE_CREDENTIALS] Preparing credentials
    at ChildProcess.completionListener (/Users/runner/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/spawn-async/build/spawnAsync.js:40:23)
[PREPARE_CREDENTIALS] Creating keychain
[...]
[RUN_FASTLANE]     Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')
[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] Exit status: 65
```

### Reproducible demo or steps to reproduce from a blank project

Here is the yml file for the action:
```yml
on:
  workflow_dispatch:
  milestone:
    types: [closed]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: latest
    
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
    
    - name: Npm install
      run: npm ci
   
    - name: Set up Xcode 14.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
      
    - name: Install fastlane
      run: brew install fastlane
    
    - name: Expo Github Action
      uses: expo/expo-github-action@7.2.0
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Create Cert File
      run: |
        mkdir -p ios/certs
        echo -n "${{ secrets.P12_CERT }}" | base64 -d > ios/certs/dist-cert.p12
      
    - name: Create mobile provision
      run: |
        echo -n "${{ secrets.MOBILE_PROVISION }}" | base64 -d > ios/certs/profile.mobileprovision
    
    - name: Expo build
      run: eas build --platform ios --profile release --local --non-interactive
```

Also, the repo I am using is public, so you can take a look on the entire build to save time. You can find it [here](https://github.com/organizachon/App/actions/runs/4128865567/jobs/7133828539).
