### ISSUE TITLE
Expo EAS Error GitHub Actions

### ISSUE THREAD

**Issue by RayanMoarkech** [expo/eas-cli#1695]
### Summary

The new version of EAS-CLI (3.6.0) introduced a bug when running on GitHub Actions. It was working fine and as expected before.

I think it is related to the added feature: https://github.com/expo/eas-cli/pull/1667

### Managed or bare?

Bare

### Environment

EAS-CLI (3.6.0)

### Error output

```
Error: Project config: Owner of project identified by 
    "extra.eas.projectId" (parkusher) does not match the logged in user (null)
     and the "owner" field is not specified. To ensure all libraries work 
    correctly, "owner": "parkusher" should be added to the project config, 
    which can be done automatically by re-running "eas init". Learn more: 
    https://expo.fyi/eas-project-id
```

### Reproducible demo or steps to reproduce from a blank project

I am using `expo/expo-github-action@v7` as a step to login.
```
            -   name: Setup Expo
                uses: expo/expo-github-action@v7
                with:
                    expo-version: latest
                    eas-version: latest
                    token: ${{ secrets.EXPO_TOKEN }}
```

Then It is failing in the step where I perform:
```
eas secret:push --scope project --env-file .env.local --force
```

Note that it was working fine before the EAS-CLI version 3.6.0 was released.
I have everything in the `app.json`, and the project ids matches.

**Comment by RayanMoarkech** [comment]
```
const actorUsername = getActorUsername(actor);
     if (!exp.owner && appForProjectId.ownerAccount.name !== actorUsername) {
```

I am not sure how this was approved. A token has no ActorUsername. If it passed the first check:
```
const appForProjectId = await AppQuery.byIdAsync(graphqlClient, localProjectId);
     if (exp.owner && exp.owner !== appForProjectId.ownerAccount.name) {
```
Then we do not need to check for the ActorUsername.

**Comment by RayanMoarkech** [comment]
It worked fine now with the following change (assigning the older was cli version):
```
            -   name: Setup Expo
                uses: expo/expo-github-action@v7
                with:
                    expo-version: latest
                    eas-version: 3.5.2
                    token: ${{ secrets.EXPO_TOKEN }}
```
