### ISSUE TITLE
Android EAS build failing on Github Actions

### ISSUE THREAD

**Issue by alessandrocapra** [expo/eas-cli#1935]
### Build/Submit details page URL

https://expo.dev/accounts/quantoz/projects/qbs-test-app/builds/6708f5ba-dec0-4b4d-b474-440039bedffc#run-gradlew

## Notes
Building locally with the same setup works

## Expected
With the provided Github actions YML file below, a build should be created for both Android and iOS and the submission should take place thanks to the `--auto-submit` flag.

```

name: Build apps through Expo EAS 

on:
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi      
      - name: Check for GOOGLE_SERVICES_JSON
        run: |
          if [ -z "${GOOGLE_SERVICES_JSON}" ]; then
            echo "You must provide a GOOGLE_SERVICES_JSON environment variable for this job. This should be a secret linked to this project's Google service account in this repo's secrets."
            exit 1
          fi
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Google Service Account
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./mobile/google-service-account.json

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          cd mobile
          npm install

      - name: Run script
        run: |
          cd mobile
          eas build --profile preview-store --platform all --non-interactive --auto-submit
```

## Actual behavior
iOS works perfectly, but the Android build fails with the error output below.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.9
    Expo Workflow: managed

Expo doctor:
Check package.json for common issues
✔ Validate global prerequisites versions
✔ Validate Expo Config
✔ Check for conflicting global packages in project
✔ Check for incompatible packages
✔ Verify prebuild support package versions are compatible
✔ Check compatible dependency versions for the installed Expo SDK

Didn't find any issues with the project!

### Error output

```
Parsing json file: /home/expo/workingdir/build/mobile/android/app/google-services.json

> Task :expo-dev-launcher:generateReleaseAssets UP-TO-DATE

> Task :expo-constants:createReleaseExpoConfig

> Task :expo-dev-launcher:packageReleaseAssets

[stderr] 
FAILURE: Build completed with 2 failures.

[stderr] 
1: Task failed with an exception.

[stderr] 
-----------

[stderr] 
* What went wrong:

[stderr] 
Execution failed for task ':app:processReleaseGoogleServices'.

[stderr] 
> Missing project_info object

[stderr] 
* Try:

[stderr] 
> Run with --stacktrace option to get the stack trace.

[stderr] 
> Run with --info or --debug option to get more log output.

[stderr] 
> Run with --scan to get full insights.

[stderr] 
==============================================================================

[stderr] 
2: Task failed with an exception.

[stderr] 
-----------

[stderr] 
* What went wrong:

[stderr] 
java.lang.StackOverflowError (no error message)

[stderr] 
* Try:

[stderr] 
> Run with --stacktrace option to get the stack trace.

[stderr] 
> Run with --info or --debug option to get more log output.

[stderr] 
> Run with --scan to get full insights.

[stderr] 
==============================================================================

[stderr] 
* Get more help at https://help.gradle.org

[stderr] 
BUILD FAILED in 3m 49s
```

### Reproducible demo or steps to reproduce from a blank project

I think it might be something simple I am missing or that I could not find in the docs, if that's not the case I will try to create a new app and create the app on the google play console.
