### ISSUE TITLE
eas build fails when using .yarnrc.yml that contains relative path to files

### ISSUE THREAD

**Issue by okkes** [expo/eas-cli#2386]
### Build/Submit details page URL

https://expo.dev/accounts/jinbu/projects/my-demo-expo-app/builds/e024d779-333e-4f13-87a9-83468cfc0d1d

### Summary

eas build fails when using .yarnrc.yml that contains relative path to files

![image](https://github.com/expo/eas-cli/assets/17009550/d664cdfe-b29a-4faf-aabf-3dbd3876f4d3)

### Managed or bare?

Managed

### Environment

not applicable

### Reproducible demo or steps to reproduce from a blank project

Not necessarily reproducing steps, but more context on the project that could help.

The .yarnrc.yml is pointing to specific yarn file as well as a plugin using relative path.
```
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
```

Folder structure:
```
.yarn
│
├───plugins
│   └───@yarnpkg
│           plugin-interactive-tools.cjs
│
└───releases
        yarn-3.5.1.cjs

.yarnrc.yml

node_modules
|....
```

.gitignore file
```
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
.DS_Store
.env
.expo/
.idea
.idea/
.pnp.*
.yarn/*
*.jks
*.key
*.mobileprovision
*.orig.*
*.p12
*.p8
dist/
node_modules/
npm-debug.*
web-build/
```
