### ISSUE TITLE
Artifact not found on IOS and Android build

### ISSUE THREAD

**Issue by nicoleRss** [expo/eas-cli#2477]
### Summary

Hi, Im trying to run a build with EAS build for IOS and Android, the build is finished and I can see it in the Build details page, For Android  I'm not able to see the download button.
![Captura de pantalla 2024-07-31 a la(s) 11 19 22 a m](https://github.com/user-attachments/assets/3445c383-8bd8-447b-bcf6-5cec82b67755)

For IOS I can see the button, but its seems is not working and Im not able to download the file.
![Captura de pantalla 2024-07-31 a la(s) 11 17 16 a m](https://github.com/user-attachments/assets/037c2162-bf9a-47c5-a026-730dc27b0955)

Running `eas build:run -p android --latest` command I see the error : `Artifacts for the latest build have expired and are no longer available, or this is not a simulator/emulator build.`, same its happening with IOS command.

### Managed or bare?

bare

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
      npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.14 => 51.0.21 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.4 => 0.67.4 
      react-navigation: ^4.4.3 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 10.2.2
      expo-cli: 6.3.10
    Expo Workflow: bare

### Error output
`Artifacts for the latest build have expired and are no longer available, or this is not a simulator/emulator build.`

### Reproducible demo or steps to reproduce from a blank project

eas build -p android --profile preview
eas build:run -p android

**Comment by szdziedzic** [comment]
Hi,

Could you send me the URLs of your builds?

**Comment by nicoleRss** [comment]
Hi @szdziedzic  

https://expo.dev/accounts/teamcore/projects/teamcorev3/builds/0af438d7-6e7d-4353-8173-479ccf9df94a
https://expo.dev/accounts/teamcore/projects/teamcorev3/builds/0697ed73-221b-4cde-922a-303afd01e3dc

Thanks

**Comment by szdziedzic** [comment]
It looks like you are using custom builds, right? Can I see your custom build config?

**Comment by szdziedzic** [comment]
@nicoleRss 

Thanks!

So basically your custom build only runs:
1. checkout
2. installs `node_modules`

at the moment. It's missing all of the other steps needed to build the app successfully. That's the reason why artifacts are not present - the app wasn't really built.

I see that you want to create an iOS simulator build and an Android Play Store build for your app, right? 

To do so you can use these configs:

`.eas/build/ios-simulator-build.yml`:
```yml
build:
  name: iOS simulator build
  steps:
    - eas/checkout

    - run:
        name: Install dependencies
        command: npm install --legacy-peer-deps

    - eas/prebuild

    - run:
        name: Install pods
        working_directory: ./ios
        command: pod install

    - eas/generate_gymfile_from_template

    - eas/run_fastlane

    - eas/find_and_upload_build_artifacts
```

`.eas/build/android-play-store-build.yml`:

```yml
build:
  name: Android Play Store build
  steps:
    - eas/checkout

    - run:
        name: Install dependencies
        command: npm install --legacy-peer-deps

    - eas/prebuild

    - eas/inject_android_credentials

    - eas/run_gradle

    - eas/find_and_upload_build_artifacts
```

and use them in your `eas.json` like:
```
{
  ... 
  "build": {
    ... 
    "android-play-store-build": {
      "android": {
        "config": "android-play-store-build.yml"
      }
    },
    "ios-simulator-build": {
      "distribution": "internal",
      "ios": {
        "simulator": true,
        "config": "ios-simulator-build.yml"
      }
    },
    ... 
  }
  ... 
}
```

To run your builds you would need to use:
1. `eas build -p ios -e ios-simulator-build`
2. `eas build -p android -e android-play-store-build`

commands.

Here are the docs if you want to learn more: https://docs.expo.dev/custom-builds/schema/#using-built-in-eas-functions-to-build-an-app
