### ISSUE TITLE
EAS Build is generating builds with different fingerprint from what it was supposed to

### ISSUE THREAD

**Issue by giorgiofellipe** [expo/eas-cli#2615]
### Summary

On EAS Build logs it shows me differences between the fingerprint calculated on my local machine (CI pipeline, actually) and the one calculated on EAS. But the message also says it will consider the one my *local machine* has calculated, but it is *NOT* true as you can see on the following screenshots.

The message I see on EAS:
![image](https://github.com/user-attachments/assets/7c28e29a-ddcb-4537-a66e-4f6ac9e0cd50)

The data I see on the generated build:
![image](https://github.com/user-attachments/assets/4898da27-2172-4ffc-80c5-1a7589d49adb)

See that the first line says `Rev.: 93743147` which is the first 8 characters of the runtime version got from expo-updates library.
This is exactly the same as the runtime calculated on EAS.

But that message on EAS said it would generate it using the fingerprint calculated on my *local machine*, so it should print there `Rev.: 6157eee1` instead.
This way my updates will never match the runtime version. I'm basically not able to send any OTA Updates...

### Managed or bare?

managed

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.8.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 26, 29, 30, 31, 32, 33, 34
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.0 => 0.17.8 
      babel-preset-expo: ^11.0.8 => 11.0.14 
      expo: ~51.0.37 => 51.0.37 
      expo-router: ^3.5.15 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.6 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

.

**Comment by giorgiofellipe** [comment]
Not sure if the error is the message that says something that is not actually true or the GHA expo/expo-github-action/continuous-deploy-fingerprint that does not calculates the same fingerprint as EAS Build does.

As you can see on the following images the update was sent using the locally calculated runtime.

Local calculated fingerprint
![image](https://github.com/user-attachments/assets/073fd70a-6ac5-4a40-a91b-98d1df252315)

EAS calculated fingerprint
![image](https://github.com/user-attachments/assets/c5525089-f765-4323-a673-7f23b9424450)

**Comment by szdziedzic** [comment]
>Also the GHA expo/expo-github-action/continuous-deploy-fingerprint does not calculate the same fingerprint as EAS Build does.

Is it possible that you have a dynamic app config that depends on env variables that have different values on GHA and EAS? 🤔

**Comment by giorgiofellipe** [comment]
@szdziedzic We do not have a dynamic app config, currently using app.json actually. Does EAS consider only EXPO_PUBLIC_ env vars? Our CI pipeline generates a .env file from all EXPO_PUBLIC_ env vars.

**Comment by szdziedzic** [comment]
EAS CLI does not work with `.env` files by itself. Only Expo CLI does as of today. So all of the variables present in the `.env` will be ignored by the `eas build` command and visible when resolving config during the build process both locally and on EAS servers. To use env vars with `eas build` you can use the `env` field in the `eas.json` config file or secrets defined on Expo servers. https://docs.expo.dev/build-reference/variables/

The one pretty confusing thing is that under the hood EAS Update does `npx expo export` and because Expo CLI supports `.env` the env vars with the `EXPO_PUBLIC` prefix from the file will be used when bundling. https://docs.expo.dev/eas-update/environment-variables/

So there is a different env vars handling behavior for EAS Update and EAS Build and Expo CLI as of today, which may lead to some issues in some cases, caused by env vars mismatch in different places, what can be the root cause of your problems? We are aware of the issue and are working towards making it better and plan to announce new env variables enhancements really soon. However, until this is done I believe the best thing you can do is to try to get the env vars to be set the same way in all of these places. Let me know if you have any more questions regarding this matter.

When it comes to handling fingerprint mismatch we had an internal discussion about it. It feels like creating a successful build with fingerprint coming from either local (from EAS CLI) or remote (from our cloud builder) sources, when there is fingerprint mismatch between these, seems to have disadvantages and may lead users to end up in non-explicit failure state, where it's ultra hard or impossible to get build to receive updates properly. As of today, we are leaning towards always explicitly failing the build when such a mismatch occurs, to make it obvious that something is broken and needs to be fixed. We shall make the change to enforce it soon. I will post updates here when it happens.

**Comment by giorgiofellipe** [comment]
@szdziedzic I really appreciate the detailed explanation about the differences between them.

However, I'm still confident that there is something else, cuz it does not make sense to be only env var mismatch between environments.
Our production pipeline gets all the env vars from our GitHub repository and generates a .env file, it also pushes the whole file to EAS, to make sure they are up to date there too. I don't see room for a mismatch between them. Check the workflow file:

```yaml
- name: Create env file
        run: |
          > .env
          echo '${{ toJson(vars) }}' | jq -r 'to_entries | .[] | select(.key | startswith("EXPO_PUBLIC_")) | "\(.key)=\(.value)"' >> .env
          cat .env

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: pnpm install

      - name: Push .env file to EAS
        run: eas secret:push --env-file=.env --scope project --force

      - name: Get config file
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.EAS_GOOGLE_PLAY_API_FILE_BASE64 }}
        run: |
          echo $GOOGLE_SERVICES_BASE64 > google-service-account.json.b64
          base64 -d -i google-service-account.json.b64 > google-service-account.json

      - name: Build & Generate OTA Update
        id: build
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          working-directory: ./monorepo/apps/mobile
          profile: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
          branch: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
```


Also, the real issue is that the EAS Build calculates a different fingerprint and sticks to it instead of using the one calculated locally (on the pipeline), it is exactly the opposite that the fingerprint mismatch warning says on EAS Build.
