### ISSUE TITLE
Slack markdown ignores new lines in environment variables

### ISSUE THREAD

**Issue by byron121** [expo/eas-cli#2728]
### Summary

Hello,

Apologies if this is the wrong repository to place this issue in. I'm trying to send a multiline Slack markdown message using the built-in eas/send_slack_message function with environment variables. I've tried various approaches, including directly adding new lines and \n characters to the variable.

I came up with the custom build schema below:

```
build:
  name: Slack send test
  steps:
    - run:
        if: ${ always() }
        command: |
          set-env TEST_SLACK_NEW_LINE_1 "This is a test with a new line
   
   
              \n\n          This is a test with a new line"
    - eas/send_slack_message:
        if: ${ always() }
        name: Send Slack message with Slack Block Kit layout
        inputs:         
          payload:
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: ${eas.env.TEST_SLACK_NEW_LINE_1} 
```

But no matter what combination of direct new lines or \n characters I include, I always get something like this in Slack:

```
This is a test with a new line \n\n This is a test with a new line
```
Strangely, passing a \n character directly to the text parameter does result in a new line. 

I'm wondering if anyone can let me know if I'm using the markdown wrong or if this is an actual bug. Any guidance would be greatly appreciated.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.9.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.3 - /opt/homebrew/bin/npm
      Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.39 => 51.0.39
      expo-router: ~3.5.24 => 3.5.24
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.13
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

This custom build schema should reproduce the error:

```
build:
  name: Slack send test
  steps:
    - run:
        if: ${ always() }
        command: |
          set-env TEST_SLACK_NEW_LINE_1 "This is a test with a new line
   
   
              \n\n          This is a test with a new line"
    - eas/send_slack_message:
        if: ${ always() }
        name: Send Slack message with Slack Block Kit layout
        inputs:         
          payload:
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: ${eas.env.TEST_SLACK_NEW_LINE_1} 
```
