### ISSUE TITLE
Unable to run eas submit for androidTV (invalid `track` field)

### ISSUE THREAD

**Issue by sebryu** [expo/eas-cli#2832]
### Summary

Currently graphql schema for eas will take enum with 4 options as `track` parameter, but when developing app for AndroidTV (with expo/react-native-tvos) there is an additional prefix added to the track name `tv:alpha` as described in [Google Play Developer docs](https://developers.google.com/android-publisher/tracks#ff-track-name).  

We have even ended app with double prefix for one of our tracks, making `tv:tv:alpha` also a correct google play track for our use case.

While I understand that the eas-cli is designed to help developers avoid shooting themselves in the foot, I suggest allowing the track parameter to accept any string, with suggested values outlined in the description.

### Managed or bare?

Bare

### Environment

expo-doctor output not relevant for this issue

### Error output

```
eas.json is not valid.
- "submit.production.android.track" must be one of [production, beta, alpha, internal]
    Error: build:list command failed
```

### Reproducible demo or steps to reproduce from a blank project

eas.json
```
{
  "cli": {
    "version": ">= 14.2.0",
    "appVersionSource": "local"
  },
  "submit": {
    "production": {
      "android": {
        "track": "tv:tv:alpha"
      }
    }
  }
}
```
And running any build command, e.g `eas build:list --limit 1 -p android --json --non-interactive`

**Comment by kibs** [comment]
@szdziedzic any chance this could be reopened?

**Comment by algoORgoal** [comment]
https://github.com/expo/eas-cli/pull/3031#issue-3089483849z
I created a pull request myself. Apparently this issue will be resolved with this pull request.

**Comment by algoORgoal** [comment]
@kibs @sebryu While expo team is working on this issue, I forkted the repo and deployed the fixed version of this on npm registry. Check it out: https://www.npmjs.com/package/@sleppy-navigators/eas-cli
`eas build --local` would work. However, `eas submit` cannot be bypassed since it eas backend validatese the track information. Therefore, I'm planning to use fastlane temporarily as below.

```yml
- name: 🏗️ Cache Fastlane gems
        uses: actions/cache@v4
        with:
          path: ~/.gem
          key: ${{ runner.os }}-gem-fastlane-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-fastlane-

      - name: 🛠️ Install Fastlane
        run: gem install fastlane

      - name: 🚀 Upload to Google Play (Fastlane)
        if: ${{ github.event.inputs.platform == 'android' && github.event.inputs.should_submit }}
        run: |
          fastlane supply \
            --aab ./output \
            --json_key credentials/android/service-account.json \
            --package_name com.sleppynavigators.studyup \
            --track track1
```
