### ISSUE TITLE
[Android Build] White screen and exit

### ISSUE THREAD

**Issue by erwanvivien** [expo/eas-cli#862]
### Summary

My app is fully functionnal on Web using `expo start --web`

However when running `eas build -p android` with

```json
{
  "cli": {
    "version": ">= 0.41.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "env": {}
    },
    "preview": {
      "distribution": "internal",
      "env": {}
    },
    "production": {
      "node": "16.13.0",
      "env": {},
      "android": {
        "buildType": "apk"
      }
    }
  },
  "submit": {
    "production": {}
  }
}
```

I retrieve the APK, download it, then the app is created, whitescreen for 0.5s and then crashes, like it terminates.

How can I get more info on the crash ? I tried using the online console from Google Chrome, didn't find it usefull :/

### Managed or bare?

I have my own React Native code

### Environment

```yml
> eas diagnostics

  EAS CLI 0.41.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.33.0.
    npmPackages:
      expo: ~44.0.0 => 44.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed
```

### Error output

No error output

### Reproducible demo or steps to reproduce from a blank project

I don't know what to give here ?
